name: soundvetx

services:
  application:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: application
    container_name: soundvetx_application
    tty: true
    ports:
      - "9002:9000"
      - "8002:8000"
      - "3002:3000"
    volumes:
      - .:/var/www
    networks:
      - local
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: soundvetx_nginx
    ports:
      - "91:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    entrypoint: sh -c "chmod -R 777 /var/www/storage/app/public && nginx -g 'daemon off;'"

  db:
    image: mysql:9
    container_name: soundvetx_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local

  adminer:
    image: adminer
    container_name: soundvetx_adminer
    ports:
      - "8088:8080"
    depends_on:
      - db
    networks:
      - local

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: soundvetx_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - local

volumes:
  db_data:

networks:
  local:
    driver: bridge
